### ISSUE TITLE
How to enable automatic rebuild for PyTorch?

### ISSUE THREAD

**Issue by raimis** [conda-forge/openmm-torch-feedstock#16]
### Comment:

TorchANI (https://github.com/conda-forge/torchani-feedstock/pull/10) and NNPOps (https://github.com/conda-forge/nnpops-feedstock/pull/3) have recieved the automated PR to rebuild for the latest PyTorch.

OpenMM-Torch should get them too as it depends on PyTorch and should be interoperable with the aformention packages.

**Comment by raimis** [comment]
Ping @mikemhenry

**Comment by hmaarrfk** [comment]
You should use the new pinning format and only depend on pytorch. Not pytorch -gpu or pytorch-cpu

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/torchsparse-feedstock/blob/main/recipe/meta.yaml

For an example.

Sorry. We are trying to loosely follow upstream when it makes sense.

**Comment by mikemhenry** [comment]
@raimis I can update the recipe so we get those automated rebuild PRs!
