### ISSUE TITLE
Packages for Python 3.10

### ISSUE THREAD

**Issue by raimis** [conda-forge/openmm-torch-feedstock#19]
### Comment:

OpenMM has packages for Python 3.10 (https://anaconda.org/conda-forge/openmm/files?version=7.7.0), OpenMM-Torch should have them too.

**Comment by mikemhenry** [comment]
This is the current error (from https://conda-forge.org/status/#python310):

openmm-torch (0) Error: not solvable ([bot CI job](https://github.com/regro/autotick-bot/actions/runs/2476045913)): main: ['osx_64_python3.10.____cpython: Encountered problems while solving:\n - package pytorch-1.11.0-cpu_py37h1fc315f_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed\n']
